global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'my_app_monitoring'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:3000']  # Adjust port if your app runs on a different port
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__metrics_path__]
        target_label: __metrics_path__
